# Generated by Django 5.0.7 on 2024-08-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('descriptions', models.TextField()),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
