# Generated by Django 5.0.7 on 2024-08-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_publication_detail_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication_detail',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
