# Generated by Django 5.0.7 on 2024-08-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_publication_detail_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='date',
        ),
        migrations.AddField(
            model_name='publication',
            name='my_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='publication_detail',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
