# Generated by Django 5.0.7 on 2024-08-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_remove_publication_date_publication_my_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_activ',
            field=models.BooleanField(null=True),
        ),
    ]
