# Generated by Django 5.0.7 on 2024-08-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_publication_is_activ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='Hashtag',
            field=models.ManyToManyField(null=True, to='Main.hashtag'),
        ),
        migrations.AddField(
            model_name='publication_detail',
            name='Hashtag',
            field=models.ManyToManyField(null=True, to='Main.hashtag'),
        ),
    ]
