# Generated by Django 5.0.7 on 2024-08-09 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_hashtag_publication_hashtag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='Hashtag',
        ),
        migrations.AddField(
            model_name='publication',
            name='Categorys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='Main.categorys'),
        ),
        migrations.AddField(
            model_name='publication',
            name='hashtag',
            field=models.ManyToManyField(null=True, to='Main.hashtag'),
        ),
    ]
