# Generated by Django 5.0.7 on 2024-08-09 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_categorys_remove_publication_hashtag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='Categorys',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='publication_detail',
            name='Categorys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='Main.categorys'),
        ),
        migrations.AddField(
            model_name='publication',
            name='Hashtag',
            field=models.ManyToManyField(null=True, to='Main.hashtag'),
        ),
    ]
