# Generated by Django 5.0.7 on 2024-08-12 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_remove_publication_categorys_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.publication')),
            ],
        ),
    ]
