# Generated by Django 5.0.7 on 2024-08-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_publicationcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
