# Generated by Django 5.0.7 on 2024-08-14 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_categorys_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='images',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='short_descriptions',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='publication_detail',
            name='Categorys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='Main.categorys', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='publication_detail',
            name='Hashtag',
            field=models.ManyToManyField(null=True, to='Main.hashtag', verbose_name='Хэштег'),
        ),
        migrations.AlterField(
            model_name='publication_detail',
            name='descriptions',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='publication_detail',
            name='images',
            field=models.ImageField(upload_to='', verbose_name='Изаброжение'),
        ),
        migrations.AlterField(
            model_name='publication_detail',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='publicationcomment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='publicationcomment',
            name='text',
            field=models.TextField(verbose_name='Тест'),
        ),
    ]
