# Generated by Django 5.0.7 on 2024-08-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_remove_publicationcomment_publication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('Email', models.EmailField(max_length=150)),
                ('Subject', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
    ]
