# Generated by Django 5.0.7 on 2024-08-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_publicationcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationcontact',
            name='Email',
            field=models.EmailField(max_length=150, null=True),
        ),
    ]
