# Generated by Django 5.0.7 on 2024-08-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_alter_publicationcontact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationcontact',
            name='Message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='publicationcontact',
            name='Subject',
            field=models.TextField(null=True),
        ),
    ]
