# Generated by Django 5.0.7 on 2024-08-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_alter_publicationcontact_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationcontact',
            name='Email',
            field=models.EmailField(default='нет', max_length=150),
        ),
        migrations.AlterField(
            model_name='publicationcontact',
            name='Message',
            field=models.TextField(default='нет'),
        ),
        migrations.AlterField(
            model_name='publicationcontact',
            name='Subject',
            field=models.TextField(default='нет'),
        ),
    ]
