# Generated by Django 5.0.7 on 2024-08-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_alter_publicationcontact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationcontact',
            name='Email',
            field=models.EmailField(default='нет', max_length=254),
        ),
    ]
