# Generated by Django 5.0.7 on 2024-08-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_alter_publicationcontact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationcontact',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='publicationcontact',
            name='Message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicationcontact',
            name='Subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
