# Generated by Django 5.0.7 on 2024-08-28 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_alter_publicationcontact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='title_ky',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='categorys',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='title_ky',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='publication',
            name='name_ky',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='publication',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='publication',
            name='short_descriptions_ky',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='publication',
            name='short_descriptions_ru',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='publication_detail',
            name='descriptions_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='publication_detail',
            name='descriptions_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='publication_detail',
            name='name_ky',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='publication_detail',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='Hashtag',
            field=models.ManyToManyField(to='Main.hashtag'),
        ),
        migrations.AlterField(
            model_name='publication_detail',
            name='Hashtag',
            field=models.ManyToManyField(to='Main.hashtag', verbose_name='Хэштег'),
        ),
        migrations.AlterField(
            model_name='publicationcomment',
            name='Publication_Detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Main.publication_detail'),
        ),
        migrations.AlterField(
            model_name='publicationcomment',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
